#Minecraft server properties
#Mon Dec 15 08:36:45 EST 2025
level-name=world
allow-nether=true
view-distance=10
spawn-monsters=true
online-mode=false
gamemode=hardcore
spawn-animals=true
pvp=true
server-ip=
max-players=20
voice-chat=true
level-seed=
server-port=25565
allow-flight=false
level-type=DEFAULT
white-list=false
motd=A Minecraft Server
